version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/mnesia/
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongodb_data:/data/db
  api:
    build: ./API
    env_file:
      - ./api/.env
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - 8000:8000
  worker:
    build: ./worker
    env_file:
      - ./worker/.env
    restart: always
    depends_on:
      - rabbitmq
      - mongo

volumes:
  rabbitmq_data:
  mongodb_data: