version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/mnesia/

volumes:
  rabbitmq_data: